project:
  type: website
  output-dir: docs
  resources:
    - data/

website:
  title: "Nicholas Gladwell"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Projects
        menu:
          - href: Portfolio1.qmd
            text: Structural Basis of Functional Selectivity in 5-HT<sub>2A</sub> and 5-HT<sub>2B</sub> Receptors

format:
  html:
    theme:
      - spacelab
    page-layout: full
    css: styles.css
    toc: true
    smooth-scroll: true



