project:
  type: website
  output-dir: docs
  resources:
    - data/
    - viewer.html

website:
  title: "Nicholas Gladwell"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Projects
        menu:
          - href: serotonin-receptor-analysis.qmd
            text: Structural Basis of Functional Selectivity in 5-HT<sub>2A</sub> and 5-HT<sub>2B</sub> Receptors
          - href: pk-monte-carlo-simulation.qmd
            text: Monte Carlo Simulation of Antibiotic PK Variability and Probability of Target Attainment

format:
  html:
    theme:
      - spacelab
    page-layout: full
    css: styles.css
    toc: true
    smooth-scroll: true
    embed-resources: false
    math: mathjax
    mathjax:
      extensions: []



